sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: zed_cloud_registered #/camera/depth_registered/points
    max_range: 2.5 #3.0 #1.5 #3.0
    point_subsample: 1
    padding_offset: 0.2 #0.3 #0.2 #0.1
    padding_scale: 1.0
    max_update_rate: 10.0 #1.0
    filtered_cloud_topic: filtered_cloud
